services:
  sim:
    build: .
    container_name: sim
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/prismadb?schema=public
    depends_on:
      - db
    networks:
      - sim

  sim-db:
    image: postgres:13
    container_name: sim-db
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prismadb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sim

networks:
  sim:

volumes:
  postgres-data:
